apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-deploy.fullname" . }}-model-worker
  labels:
    {{- include "k8s-deploy.labels" . | nindent 4 }}
    app.kubernetes.io/component: model-worker
spec:
  replicas: {{ .Values.modelWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-deploy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: model-worker
  template:
    metadata:
      labels:
        {{- include "k8s-deploy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: model-worker
    spec:
      containers:
        - name: model-worker
          image: "{{ .Values.modelWorker.image.repository }}:{{ .Values.modelWorker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.modelWorker.image.pullPolicy }}
          env:
            - name: TRANSFORMERS_CACHE
              value: {{ .Values.modelWorker.env.TRANSFORMERS_CACHE }}
          volumeMounts:
            - mountPath: {{ .Values.modelWorker.env.TRANSFORMERS_CACHE }}
              name: model-cache
          resources:
            {{- toYaml .Values.modelWorker.resources | nindent 12 }}
      volumes:
        - name: model-cache
          emptyDir: {}