apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-deploy.fullname" . }}-model-worker
  labels:
    {{- include "k8s-deploy.labels" . | nindent 4 }}
    app.kubernetes.io/component: model-worker
spec:
  type: {{ .Values.modelWorker.service.type }}
  selector:
    {{- include "k8s-deploy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: model-worker
  ports:
    - protocol: TCP
      port: {{ .Values.modelWorker.service.port }}
      targetPort: {{ .Values.modelWorker.service.port }}