apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-deploy.fullname" . }}-web
  labels:
    {{- include "k8s-deploy.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "k8s-deploy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - protocol: TCP
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}