apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.0.0
    helm:
      values: |
        crds:
          enabled: false
        prometheus-operator:
          enabled: true
        alertmanager:
          alertmanagerSpec:
            externalUrl: http://alertmanager.prtest.shop
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - alertmanager.prtest.shop
            paths:
              - /
            tls:
              - secretName: alertmanager-prtest-shop-tls
                hosts:
                  - alertmanager.prtest.shop
        grafana:
          existingSecret: "grafana-admin-credentials"
          admin:
            existingSecret: "grafana-admin-credentials"
            userKey: adminUser
            passwordKey: adminPassword
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - grafana.prtest.shop
            tls:
              - secretName: grafana-prtest-shop-tls
                hosts:
                  - grafana.prtest.shop
        prometheus:
          prometheusSpec:
            externalUrl: http://prometheus.prtest.shop
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - prometheus.prtest.shop
            paths:
              - /
            tls:
              - secretName: prometheus-prtest-shop-tls
                hosts:
                  - prometheus.prtest.shop
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true